// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PublishEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['PublishEvent'](arg1, arg2, arg3);
}

export function SubscribeToEvent(arg1, arg2) {
  return window['go']['main']['App']['SubscribeToEvent'](arg1, arg2);
}

export function UnsubscribeFromEvent(arg1, arg2) {
  return window['go']['main']['App']['UnsubscribeFromEvent'](arg1, arg2);
}
