// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function PublishEvent(arg1:string,arg2:any,arg3:string):Promise<void>;

export function SubscribeToEvent(arg1:string,arg2:any):Promise<void>;

export function UnsubscribeFromEvent(arg1:string,arg2:any):Promise<void>;
